id: I50647920
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T00:00:49.306786'
last_modified: '2022-06-19T00:00:49.306800'
parser: null
source_metadata:
  title: A mes zhabss (1597–1659) Presentation on the Hevajra Practice according to
    the Ngor pa and rDzong pa
  author: ཨ་མྱེས་ཞབས་ངག་དབང་ཀུན་དགའ་བསོད་ནམས།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2015-07-12);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Guru Lama, Sachen International, Kathmandu (Nepal) (si)
  - Editorial process:Mathias Fermer (mf), བྱམས་པ་ཆོས་དབང་། (Dehradun) (jc)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/1266
  bases:
    b601:
      title: A mes zhabss (1597–1659) Presentation on the Hevajra Practice according
        to the Ngor pa and rDzong pa
      order: 1
      base_file: b601.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
